### ISSUE TITLE
Comments on union type variants get merged

### ISSUE THREAD

**Issue by ehamberg** [old-reliable/steamroller#17]
On (a few) typespecs for union types I have a comment after each variant. steamroller will merge the comments, making the end result quite confusing.

```diff
--type status() :: draft      % - not published
-                | pending    % - currently being reviewed
-                | rejected   % - failed review
-                | scheduled  % - reviewed and scheduled to start in the future
-                | active     % - reviewed and live
-                | inactive   % - stopped
-                .
+-type status() :: % - not published
+                % - currently being reviewed
+                % - failed review
+                % - reviewed and scheduled to start in the future
+                % - reviewed and live
+                % - stopped
+                draft | pending | rejected | scheduled | active | inactive.
```

**Comment by dtip** [comment]
Oh boy that's disgusting. Will investigate.

**Comment by dtip** [comment]
This is "fixed" by some loose definition. Comments are no-longer merged but in-line comments are currently unsupported so all your comments will be moved to the line above where they currently are.

I plan to add support for in-line comments at some point, but am out of time for today!

**Comment by dtip** [comment]
I'll close this and open a new issue to add support for in-line comments
