### ISSUE TITLE
formatting check failing on github actions

### ISSUE THREAD

**Issue by shamis** [old-reliable/steamroller#22]
Strangely the formatting check is failing on github actions https://github.com/KonnexionsGmbH/jpparse/pull/12/checks?check_run_id=638440875#step:5:1

Its working as expected on travis and locally.

**Comment by dtip** [comment]
The formatting check is telling the truth - `jpparse/src/jpparse.erl` is not formatted.

It looks like this file isn't version controlled but is instead generated at compile time. It's not formatted with Steamroller when it's generated.

If you run the formatting check before you compile, I'm guessing the problem would go away!

**Comment by dtip** [comment]
It looks like on your Travis build you're checking the formatting before you compile

**Comment by shamis** [comment]
thanks, sorry my bad.

**Comment by dtip** [comment]
No problem - happy to help!
