### ISSUE TITLE
skipping files - when hrl files are not found

### ISSUE THREAD

**Issue by shamis** [old-reliable/steamroller#6]
In project https://github.com/K2InformaticsGmbH/dderl running steamroll skips all files with include_lib defined.

```
$ rebar3 steamroll
===> Steamrolling code...
===> Steamroller Warn: File: /Users/shamisshukoor/repo/tmp/dderl/src/dderl.hrl: epp error {include,
                                                                                                  lib,
                                                                                                  "imem/include/imem_meta.hrl"} on line 4. Skipping...
===> Steamroller Warn: File: /Users/shamisshukoor/repo/tmp/dderl/src/dderloci.hrl: epp error {include,
                                                                                                     lib,
                                                                                                     "imem/include/imem_meta.hrl"} on line 4. Skipping...
===> Steamroller Warn: File: /Users/shamisshukoor/repo/tmp/dderl/src/dderl.erl: epp error {include,
                                                                                                  lib,
                                                                                                  "imem/include/imem_meta.hrl"} on line 4. Skipping...
===> Steamroller Warn: File: /Users/shamisshukoor/repo/tmp/dderl/src/dderl_access_logger.erl: epp error {include,
                                                                                                                lib,
                                                                                                                "imem/include/imem_meta.hrl"} on line 4. Skipping...
```

This happens, even though compilation works fine. 
Is there something that has to be changed ?

**Comment by dtip** [comment]
Thanks for the bug report @shamis !

I've made steamroller better at finding include files: https://github.com/old-reliable/steamroller/commit/67ed34834892eba3b4e3bb1f713e0c0a756db54c

Will release v0.11.4 shortly which will include the fix for this :)

**Comment by shamis** [comment]
thanks for the quick response,
tried it but it didnt seem to work - https://github.com/old-reliable/steamroller/commit/67ed34834892eba3b4e3bb1f713e0c0a756db54c#r36709708

Also for some reason the execution gets suck/loop on file [dderl_rest](https://github.com/K2InformaticsGmbH/dderl/blob/master/src/dderl_rest.erl). Without this file it works fine.

**Comment by dtip** [comment]
Hmm yeah you're quite right. Looks like that file has some code inside an `ifdef` which steamroller wasn't expecting. v0.11.5 should fix it :)

**Comment by shamis** [comment]
thanks, its working fine now

**Comment by dtip** [comment]
Great stuff! Please open another issue if you run into any more trouble :)
